spring:
  data:
    mongodb:
      uri: mongodb://root:1234@mongodbService:27017/shareDB?authSource=admin

#      host: mongodbService
#      port: 27017
#      username: root
#      password: 1234
#      database: shareDB

