FROM python:3.9
COPY . .
RUN pip3 install flask
RUN pip3 install tensorflow
RUN pip3 install pillow
RUN pip3 install boto3

WORKDIR .

ENV FLASK_APP=app.py
CMD ["python3", "-m", "flask", "run","--host=0.0.0.0"]