version : "3.8"
services:
  mongodbService:
    image: mongo:4.4.5
    container_name: mongodbService
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=shareDB


  backend:
    container_name: backend
    #env_file:
    #  ../Backend/.env
    build:
      context: ../shareNote
    ports:
      - "8080:8080"
      - "5005:5005"
    #environment:
      #S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      #S3_SECRET_KEY: ${S3_SECRET_KEY}
      #RABBIT_HOST: rabbitmq
    depends_on:
      - mongodbService
    restart: on-failure



